name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    name: Deploy static site to Cloudflare
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy

  deploy-functions:
    runs-on: ubuntu-latest
    name: Deploy functions to Firebase
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install functions dependencies
        working-directory: functions
        run: npm ci
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}